<a href="https://colab.research.google.com/github/arghac14/Customer-churn-analysis/blob/master/Kmodes_and_kprototype_clustering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
import seaborn as sb

In [3]:
import io
from google.colab import files
uploaded = files.upload()


Saving bank numeric.xlsx to bank numeric.xlsx


In [114]:
import io
df = pd.read_excel(io.BytesIO(uploaded['bank numeric.xlsx']))
df.head(10)

age   job    marital    education   ...   pdays    previous    poutcome   Y
0    30      1          0            2  ...       -1           0           0  0
1    33     10          0            1  ...      339           4           2  0
2    35      2          2            3  ...      330           1           2  0
3    30      2          0            3  ...       -1           0           0  0
4    59      6          0            1  ...       -1           0           0  0
5    35      2          2            3  ...      176           3           2  0
6    36      7          0            3  ...      330           2           1  0
7    39      9          0            1  ...       -1           0           0  0
8    41      4          0            3  ...       -1           0           0  0
9    43     10          0            2  ...      147           2           2  0

[10 rows x 17 columns]

#### Spliting the dataset into two parts with different values of Y (0 or 1)

In [115]:
df_1=df[df['Y']==1]
df_1.head()

age   job    marital    education   ...   pdays    previous    poutcome   Y
13    20      5          2            1  ...       -1           0           0  1
30    68      8          1            1  ...       -1           0           0  1
33    32      2          2            3  ...       -1           0           0  1
34    49      9          0            3  ...       -1           0           0  1
36    78      8          1            2  ...       -1           0           0  1

[5 rows x 17 columns]

In [116]:
df_0=df[df['Y']==0]
df_0.head()

age   job    marital    education   ...   pdays    previous    poutcome   Y
0    30      1          0            2  ...       -1           0           0  0
1    33     10          0            1  ...      339           4           2  0
2    35      2          2            3  ...      330           1           2  0
3    30      2          0            3  ...       -1           0           0  0
4    59      6          0            1  ...       -1           0           0  0

[5 rows x 17 columns]

In [117]:
df.describe()

age         job   ...    poutcome             Y
count  4521.000000  4521.000000  ...  4521.000000  4521.000000
mean     41.170095     6.332891  ...     0.345941     0.115240
std      10.576211     3.257802  ...     0.783817     0.319347
min      19.000000     0.000000  ...     0.000000     0.000000
25%      33.000000     2.000000  ...     0.000000     0.000000
50%      39.000000     6.000000  ...     0.000000     0.000000
75%      49.000000     9.000000  ...     0.000000     0.000000
max      87.000000    11.000000  ...     3.000000     1.000000

[8 rows x 17 columns]

In [118]:
!pip install kmodes

## Kmode clustering for the dataset where Y=0

In [0]:
num_of_clusters=10

In [120]:
from kmodes.kmodes import KModes


km = KModes(n_clusters=num_of_clusters, init='Huang', n_init=5, verbose=1)

clusters = km.fit_predict(df_0)

df_0_centroids=km.cluster_centroids_

Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 1610, cost: 26571.0
Run 1, iteration: 2/100, moves: 59, cost: 26571.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 2, iteration: 1/100, moves: 1030, cost: 27038.0
Run 2, iteration: 2/100, moves: 114, cost: 27021.0
Run 2, iteration: 3/100, moves: 2, cost: 27021.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 3, iteration: 1/100, moves: 1239, cost: 26518.0
Run 3, iteration: 2/100, moves: 75, cost: 26518.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 4, iteration: 1/100, moves: 895, cost: 27046.0
Run 4, iteration: 2/100, moves: 93, cost: 27044.0
Run 4, iteration: 3/100, moves: 1, cost: 27044.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 5, iteration: 1/100, moves: 1087, cost: 26762.0
Run 5, iteration: 2/100, moves: 255, cost:

In [121]:
print("Centroids:\n")
print(df_0_centroids)

Centroids:

[[ 40   2   2   1   0   0   1   0   2  17  11  65   1  -1   0   0   0]
 [ 34   2   2   3   0   0   0   0   2  21   8  71   2  -1   0   0   0]
 [ 39   6   0   1   0   0   1   0   2  14   7 143   1  -1   0   0   0]
 [ 45   6   0   2   0   0   0   0   0  20   6  29   2  -1   0   0   0]
 [ 32   6   0   1   0   0   1   0   0  15   5  57   1  -1   0   0   0]
 [ 36   9   0   3   0   0   1   0   0   6   6  74   1  -1   0   0   0]
 [ 55   2   0   3   0   0   0   0   2  30   7 127   2  -1   0   0   0]
 [ 56   2   1   3   0   2   1   0   2  18   5   9   1  -1   0   0   0]
 [ 37   9   0   1   0   0   0   0   2  20   8 106   2  -1   0   0   0]
 [ 33   6   0   1   0   0   1   0   2  20   4  61   2  -1   0   0   0]]


## Kmode clustering for the dataset where Y=1

In [123]:
from kmodes.kmodes import KModes


km = KModes(n_clusters=num_of_clusters, init='Huang', n_init=5, verbose=1)

clusters = km.fit_predict(df_1)

df_1_centroids=km.cluster_centroids_

Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 164, cost: 3678.0
Run 1, iteration: 2/100, moves: 31, cost: 3677.0
Run 1, iteration: 3/100, moves: 0, cost: 3677.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 2, iteration: 1/100, moves: 196, cost: 3677.0
Run 2, iteration: 2/100, moves: 58, cost: 3645.0
Run 2, iteration: 3/100, moves: 15, cost: 3640.0
Run 2, iteration: 4/100, moves: 0, cost: 3640.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 3, iteration: 1/100, moves: 181, cost: 3708.0
Run 3, iteration: 2/100, moves: 30, cost: 3703.0
Run 3, iteration: 3/100, moves: 2, cost: 3703.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 4, iteration: 1/100, moves: 136, cost: 3676.0
Run 4, iteration: 2/100, moves: 24, cost: 3674.0
Run 4, iteration: 3/100, moves: 0, cost: 3674.0
Init: initializing centroids
Init: initiali

In [124]:
print("Centroids:\n")
print(df_1_centroids)

Centroids:

[[  34    2    0    3    0 -247    1    0    2    5    5  262    1   92
     2    1    1]
 [  28    8    0    1    0    0    0    0    2    5    7  397    1   -1
     0    0    1]
 [  36    2    0    3    0  495    0    0    2   18    8  328    2   -1
     0    0    1]
 [  37    9    0    1    0    0    0    0    2   15    4  250    1  182
     1    3    1]
 [  34    2    0    3    0    0    0    0    2   30    4   76    1   -1
     0    0    1]
 [  32    9    0    1    0  668    1    0    2   13    5  224    2   -1
     0    0    1]
 [  32    6    0    1    0 -887    1    0    2   18    5  442    1   -1
     0    0    1]
 [  27    9    2    1    0  133    0    0    2   20    2  171    1   -1
     0    0    1]
 [  29   11    0    1    0    0    1    0    0   28    5  543    1   -1
     0    0    1]
 [  35    2    2    3    0    0    1    0    2   16    7   97    1   -1
     0    0    1]]


## Kprotoypes clustering for the dataset where Y=0

In [125]:
import numpy as np
from kmodes.kprototypes import KPrototypes


kproto = KPrototypes(n_clusters=num_of_clusters, init='Cao', verbose=2)
clusters = kproto.fit_predict(df_0, categorical=[2,3,4,6,7,8,12,14,15,16])


# Print cluster centroids of the trained model.
print(kproto.cluster_centroids_)
# Print training statistics
print(kproto.cost_)
print(kproto.n_iter_)


Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 1, iteration: 1/100, moves: 1508, ncost: 6846218637.664771
Run: 1, iteration: 2/100, moves: 388, ncost: 5493632871.692671
Run: 1, iteration: 3/100, moves: 284, ncost: 4639487035.2929325
Run: 1, iteration: 4/100, moves: 219, ncost: 3994334625.9347925
Run: 1, iteration: 5/100, moves: 264, ncost: 3528992651.1967626
Run: 1, iteration: 6/100, moves: 180, ncost: 3394097195.7646995
Run: 1, iteration: 7/100, moves: 115, ncost: 3360395990.7746572
Run: 1, iteration: 8/100, moves: 108, ncost: 3324343211.5961213
Run: 1, iteration: 9/100, moves: 113, ncost: 3302417398.5605874
Run: 1, iteration: 10/100, moves: 103, ncost: 3274600268.5661197
Run: 1, iteration: 11/100, moves: 92, ncost: 3238554221.599668
Run: 1, iteration: 12/100, moves: 91, ncost: 3203701220.9726562
Run: 1, iteration: 13/100, moves: 95, ncost: 3067281768.615075
Run: 1, iteration: 14/100, moves: 98, ncost: 3044070914.894383
Run: 1, iteration: 15/100, 

In [126]:
# myList = list(np.rint(np.around(kproto.cluster_centroids_[0][0],1)))
# myList
for i in range(5):
  print("\nCentroid:",i+1,"\n")
  print(list(np.rint(np.around(kproto.cluster_centroids_[0][i],1))), end=' ')
  print(list(np.rint(np.around(kproto.cluster_centroids_[1][i],1))))
  


Centroid: 1 

[39.0, 7.0, -502.0, 17.0, 6.0, 238.0, 27.0] [0.0, 1.0, 0.0, 1.0, 0.0, 2.0, 1.0, 0.0, 0.0, 0.0]

Centroid: 2 

[43.0, 6.0, 5820.0, 16.0, 7.0, 234.0, 46.0] [0.0, 1.0, 0.0, 1.0, 0.0, 2.0, 1.0, 0.0, 0.0, 0.0]

Centroid: 3 

[42.0, 6.0, 2038.0, 16.0, 6.0, 222.0, 41.0] [0.0, 1.0, 0.0, 1.0, 0.0, 2.0, 1.0, 0.0, 0.0, 0.0]

Centroid: 4 

[41.0, 6.0, 921.0, 16.0, 6.0, 252.0, 39.0] [0.0, 1.0, 0.0, 1.0, 0.0, 2.0, 1.0, 0.0, 0.0, 0.0]

Centroid: 5 

[43.0, 5.0, 14498.0, 17.0, 8.0, 208.0, 41.0] [0.0, 3.0, 0.0, 0.0, 0.0, 2.0, 1.0, 0.0, 0.0, 0.0]


#### Kprototypes clustering for the dataset where Y=1

In [90]:
import numpy as np
from kmodes.kprototypes import KPrototypes


kproto = KPrototypes(n_clusters=5, init='Cao', verbose=2)
clusters = kproto.fit_predict(df_1, categorical=[2,3,4,6,7,8,12,14,15,16])


# Print cluster centroids of the trained model.
print(kproto.cluster_centroids_)
# Print training statistics
print(kproto.cost_)
print(kproto.n_iter_)


Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 1, iteration: 1/100, moves: 96, ncost: 597293494.9140183
Run: 1, iteration: 2/100, moves: 50, ncost: 449243143.0250518
Run: 1, iteration: 3/100, moves: 30, ncost: 388109536.9981037
Run: 1, iteration: 4/100, moves: 14, ncost: 344332621.2153068
Run: 1, iteration: 5/100, moves: 7, ncost: 318783812.95202005
Run: 1, iteration: 6/100, moves: 0, ncost: 318783812.95202005
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 2, iteration: 1/100, moves: 105, ncost: 882636280.4004408
Run: 2, iteration: 2/100, moves: 65, ncost: 682581646.3742691
Run: 2, iteration: 3/100, moves: 37, ncost: 623596148.4660655
Run: 2, iteration: 4/100, moves: 30, ncost: 587723221.382908
Run: 2, iteration: 5/100, moves: 33, ncost: 554144337.5314583
Run: 2, iteration: 6/100, moves: 30, ncost: 515854178.67469317
Run: 2, iteration: 7/100, moves: 27, ncost: 479676595.5569815
Run: 2, iteration: 8/100, moves: 

In [129]:
# myList = list(np.rint(np.around(kproto.cluster_centroids_[0][0],1)))
# myList
for i in range(num_of_clusters):
  print("\nCentroid:",i+1,"\n\n\t\t(Numeric)\t\t\t\t\t\t(Categorical)\n")
  print(list(np.rint(np.around(kproto.cluster_centroids_[0][i],1))), end=' ')
  print(list(np.rint(np.around(kproto.cluster_centroids_[1][i],1))))
  


Centroid: 1 

		(Numeric)						(Categorical)

[39.0, 7.0, -502.0, 17.0, 6.0, 238.0, 27.0] [0.0, 1.0, 0.0, 1.0, 0.0, 2.0, 1.0, 0.0, 0.0, 0.0]

Centroid: 2 

		(Numeric)						(Categorical)

[43.0, 6.0, 5820.0, 16.0, 7.0, 234.0, 46.0] [0.0, 1.0, 0.0, 1.0, 0.0, 2.0, 1.0, 0.0, 0.0, 0.0]

Centroid: 3 

		(Numeric)						(Categorical)

[42.0, 6.0, 2038.0, 16.0, 6.0, 222.0, 41.0] [0.0, 1.0, 0.0, 1.0, 0.0, 2.0, 1.0, 0.0, 0.0, 0.0]

Centroid: 4 

		(Numeric)						(Categorical)

[41.0, 6.0, 921.0, 16.0, 6.0, 252.0, 39.0] [0.0, 1.0, 0.0, 1.0, 0.0, 2.0, 1.0, 0.0, 0.0, 0.0]

Centroid: 5 

		(Numeric)						(Categorical)

[43.0, 5.0, 14498.0, 17.0, 8.0, 208.0, 41.0] [0.0, 3.0, 0.0, 0.0, 0.0, 2.0, 1.0, 0.0, 0.0, 0.0]

Centroid: 6 

		(Numeric)						(Categorical)

[46.0, 6.0, 23506.0, 13.0, 7.0, 140.0, 64.0] [0.0, 3.0, 0.0, 1.0, 0.0, 2.0, 1.0, 0.0, 0.0, 0.0]

Centroid: 7 

		(Numeric)						(Categorical)

[51.0, 6.0, 56616.0, 7.0, 9.0, 205.0, -1.0] [0.0, 2.0, 0.0, 0.0, 0.0, 2.0, 1.0, 0.0, 0.0, 0.0]

Cent